-- Auto-generated by generate_mock_data.py (seed=42).
-- Window: 2026-04-18 04:30:00 to 2026-04-18 20:00:00 UTC (aligned with InfluxDB data range).
-- Apply AFTER 02_master_data.sql. Single transaction.

BEGIN;

-- 3 rows -> production_order
INSERT INTO production_order (order_id, line_id, product_id, qty_ordered, planned_start, planned_end) VALUES
    (1, 1, 1, 357, '2026-04-18 04:30:00', '2026-04-18 20:00:00'),
    (2, 1, 2, 312, '2026-04-18 04:30:00', '2026-04-18 20:00:00'),
    (3, 1, 3, 440, '2026-04-18 04:30:00', '2026-04-18 20:00:00');

-- 6 rows -> production_batch
INSERT INTO production_batch (batch_id, order_id, qty_planned, qty_out, start_time, end_time) VALUES
    (1, 1, 78, 76, '2026-04-18 04:30:41', '2026-04-18 06:37:04'),
    (2, 3, 53, 52, '2026-04-18 07:07:48', '2026-04-18 09:28:27'),
    (3, 1, 104, 103, '2026-04-18 09:41:42', '2026-04-18 11:49:18'),
    (4, 1, 108, 104, '2026-04-18 12:17:40', '2026-04-18 14:44:18'),
    (5, 1, 55, 54, '2026-04-18 14:53:18', '2026-04-18 17:15:16'),
    (6, 3, 96, NULL, '2026-04-18 17:25:48', NULL);

-- 5 rows -> qc_record
INSERT INTO qc_record (qc_id, batch_id, qty_sampled, qty_passed, qty_failed, inspected_at) VALUES
    (1, 1, 4, 3, 1, '2026-04-18 06:49:04'),
    (2, 2, 3, 3, 0, '2026-04-18 09:33:27'),
    (3, 3, 5, 5, 0, '2026-04-18 12:19:18'),
    (4, 4, 5, 5, 0, '2026-04-18 15:11:18'),
    (5, 5, 3, 3, 0, '2026-04-18 17:34:16');

-- Sync sequences past explicit IDs.
SELECT setval('production_order_order_id_seq', (SELECT MAX(order_id) FROM production_order));
SELECT setval('production_batch_batch_id_seq', (SELECT MAX(batch_id) FROM production_batch));
SELECT setval('qc_record_qc_id_seq', (SELECT MAX(qc_id) FROM qc_record));

COMMIT;
