from __future__ import annotations
import random
from datetime import datetime, timedelta
from pathlib import Path


"""สร้าง mock OLTP data ตาม schema ใหม่ (6 ตาราง)

Output: db_module/db_sources/supabases_sql_query/mock/03_mock_data.sql
Deterministic ด้วย SEED คงที่ — reproducible

สำคัญ: time window ของ batch ต้อง **ตรงกับช่วงเวลาที่ InfluxDB (AWS) มีข้อมูล**
เพราะ FACT_SENSOR ต้อง JOIN กับ FACT_PRODUCTION ตาม time window
ถ้า mock batch อยู่นอกช่วง Influx → FACT_SENSOR จะว่าง

InfluxDB range (query เมื่อ 2026-04-19):
  earliest: 2026-04-18 04:27 UTC
  latest:   2026-04-18 20:02 UTC
  machines: M01/M02/M03
  metrics:  temperature_c, machine_state_num, cycle_count,
            vibration_g, current_a, voltage_v

Mock scope:
- 1 วัน (2026-04-18 UTC) ครอบคลุม window InfluxDB
- 5 batch เสร็จสมบูรณ์ + 1 batch in-progress (end_time NULL)
- QC record 1:1 กับ batch ที่เสร็จ (สุ่ม 5% ของ qty_out)
"""


# ---- Parameters ----
SEED = 42
# ช่วง window ต้องอยู่ใน InfluxDB data range
INFLUX_EARLIEST = datetime(2026, 4, 18, 4, 30)   # UTC
INFLUX_LATEST   = datetime(2026, 4, 18, 20, 0)   # UTC
TOTAL_BATCHES = 6                 # 5 finished + 1 in-progress
QTY_PER_BATCH_MIN = 50
QTY_PER_BATCH_MAX = 120
QC_SAMPLE_RATE = 0.05             # QC สุ่ม 5% ตาม RQ
DEFECT_RATE = 0.04                # ~4% failed

PRODUCTS = [1, 2, 3]
LINE_ID = 1

OUT_PATH = Path(__file__).parent / "03_mock_data.sql"


# ---- SQL helpers ----

def _sql_str(v) -> str:
    """แปลง Python value เป็น SQL literal"""
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, datetime):
        return f"'{v.strftime('%Y-%m-%d %H:%M:%S')}'"
    return "'" + str(v).replace("'", "''") + "'"


def _bulk_insert(table: str, cols: list[str], rows: list[tuple], out) -> None:
    if not rows:
        return
    out.write(f"-- {len(rows)} rows -> {table}\n")
    out.write(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n")
    chunks = ["    (" + ", ".join(_sql_str(v) for v in row) + ")" for row in rows]
    out.write(",\n".join(chunks))
    out.write(";\n\n")


# ---- Generators ----

def gen_orders():
    """1 order ต่อ product — วาง plan ครอบ window เดียวกัน"""
    orders = []
    for i, product_id in enumerate(PRODUCTS, start=1):
        orders.append((
            i, LINE_ID, product_id,
            random.randint(300, 600),
            INFLUX_EARLIEST,
            INFLUX_LATEST,
        ))
    return orders


def gen_batches(order_ids: list[int]):
    """สร้าง batch แบบเรียงกัน ให้ start/end อยู่ใน Influx window

    - batch ตัวสุดท้าย (index = TOTAL_BATCHES-1) = in-progress (end_time NULL)
    - ที่เหลือ = finished + QC
    """
    batches = []
    qc_records = []

    # แบ่ง window เท่า ๆ กัน: 15.5 ชม. / 6 ≈ 2.5 ชม./batch
    total_seconds = (INFLUX_LATEST - INFLUX_EARLIEST).total_seconds()
    slot = total_seconds / TOTAL_BATCHES

    qc_id = 1
    for i in range(TOTAL_BATCHES):
        batch_id = i + 1
        order_id = random.choice(order_ids)
        qty_planned = random.randint(QTY_PER_BATCH_MIN, QTY_PER_BATCH_MAX)

        start_time = INFLUX_EARLIEST + timedelta(seconds=i * slot + random.uniform(0, 300))
        # ใช้เวลา 80-95% ของ slot (เผื่อ gap ระหว่าง batch)
        duration_sec = slot * random.uniform(0.80, 0.95)

        is_finished = i < TOTAL_BATCHES - 1
        if is_finished:
            end_time = start_time + timedelta(seconds=duration_sec)
            qty_out = int(qty_planned * random.uniform(0.95, 1.0))
        else:
            end_time = None
            qty_out = None

        batches.append((
            batch_id, order_id, qty_planned, qty_out, start_time, end_time,
        ))

        if is_finished and qty_out:
            qty_sampled = max(1, int(round(qty_out * QC_SAMPLE_RATE)))
            qty_failed = sum(
                1 for _ in range(qty_sampled)
                if random.random() < DEFECT_RATE
            )
            qty_passed = qty_sampled - qty_failed
            inspected_at = end_time + timedelta(minutes=random.randint(5, 30))
            qc_records.append((
                qc_id, batch_id, qty_sampled, qty_passed, qty_failed, inspected_at,
            ))
            qc_id += 1

    return batches, qc_records


# ---- Main ----

def main() -> None:
    random.seed(SEED)

    orders = gen_orders()
    order_ids = [o[0] for o in orders]
    batches, qc_records = gen_batches(order_ids)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w") as out:
        out.write(
            f"-- Auto-generated by generate_mock_data.py (seed={SEED}).\n"
            f"-- Window: {INFLUX_EARLIEST} to {INFLUX_LATEST} UTC "
            f"(aligned with InfluxDB data range).\n"
            f"-- Apply AFTER 02_master_data.sql. Single transaction.\n\n"
            f"BEGIN;\n\n"
        )

        _bulk_insert(
            "production_order",
            ["order_id", "line_id", "product_id", "qty_ordered",
             "planned_start", "planned_end"],
            orders, out,
        )
        _bulk_insert(
            "production_batch",
            ["batch_id", "order_id", "qty_planned", "qty_out",
             "start_time", "end_time"],
            batches, out,
        )
        _bulk_insert(
            "qc_record",
            ["qc_id", "batch_id", "qty_sampled", "qty_passed", "qty_failed",
             "inspected_at"],
            qc_records, out,
        )

        out.write(
            "-- Sync sequences past explicit IDs.\n"
            "SELECT setval('production_order_order_id_seq', "
            "(SELECT MAX(order_id) FROM production_order));\n"
            "SELECT setval('production_batch_batch_id_seq', "
            "(SELECT MAX(batch_id) FROM production_batch));\n"
            "SELECT setval('qc_record_qc_id_seq', "
            "(SELECT MAX(qc_id) FROM qc_record));\n\n"
            "COMMIT;\n"
        )

    finished_count = sum(1 for b in batches if b[5] is not None)
    print(f"Wrote {OUT_PATH}")
    print(f"  Window: {INFLUX_EARLIEST} → {INFLUX_LATEST} UTC")
    print(f"  production_order  {len(orders):>4}")
    print(f"  production_batch  {len(batches):>4}   "
          f"({finished_count} finished, {len(batches) - finished_count} in-progress)")
    print(f"  qc_record         {len(qc_records):>4}")
    print("\nBatch timeline:")
    for b in batches:
        print(f"  batch_id={b[0]:<3} start={b[4]}  end={b[5]}  qty_out={b[3]}")


if __name__ == "__main__":
    main()
